apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.externalPort }}
      name: http
      targetPort: {{ .Values.service.internalPort }}      
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}